<?php
namespace HybridRox\WorkoutFilters\CLI;

use HybridRox\WorkoutFilters\CPT;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Seeder {
	public function __construct() {
		if ( defined( 'WP_CLI' ) && WP_CLI ) {
			\WP_CLI::add_command( 'hybridrox seed-workouts', array( $this, 'seed' ) );
		}
	}

	public function seed( $args, $assoc_args ) {
		$count = isset( $assoc_args['count'] ) ? max( 1, (int) $assoc_args['count'] ) : 60;
		$pool  = array(
			'workout_type'  => array( 'interval', 'circuit', 'emom', 'amrap' ),
			'equipment'     => array( 'sled', 'kettlebell', 'rower', 'dumbbell', 'sandbag', 'none' ),
			'modality'      => array( 'strength', 'conditioning', 'hyrox-specific' ),
			'goal'          => array( 'endurance', 'power', 'speed', 'fat-loss' ),
			'difficulty'    => array( 'beginner', 'intermediate', 'advanced' ),
			'location'      => array( 'gym', 'home', 'track' ),
			'hyrox_station' => array( 'ski-erg', 'sled-push', 'burpee-broad-jump', 'row', 'farmer-carry' ),
		);

		for ( $i = 1; $i <= $count; $i++ ) {
			$post_id = wp_insert_post(
				array(
					'post_type'    => 'workout',
					'post_status'  => 'publish',
					'post_title'   => sprintf( 'Hybrid Workout %d', $i ),
					'post_excerpt' => 'Demo workout generated by HybridRox seeder.',
				)
			);

			if ( is_wp_error( $post_id ) || ! $post_id ) {
				continue;
			}

			foreach ( CPT::taxonomies() as $taxonomy ) {
				$choices = $pool[ $taxonomy ];
				shuffle( $choices );
				$pick = array_slice( $choices, 0, wp_rand( 1, 2 ) );
				wp_set_object_terms( $post_id, $pick, $taxonomy );
			}

			update_post_meta( $post_id, 'duration_minutes', wp_rand( 20, 90 ) );
			update_post_meta( $post_id, 'time_cap_minutes', wp_rand( 0, 1 ) ? wp_rand( 25, 100 ) : '' );
			update_post_meta( $post_id, 'popularity_score', wp_rand( 1, 100 ) );
		}

		\WP_CLI::success( sprintf( 'Seeded %d workouts.', $count ) );
	}
}
